version: '3.9'
name: auth_mailer
services:
  mongodb:
    container_name: auth_mailer_mongodb
    image: mongo:latest
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_DATABASE=auth-mailer
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

  api:
    container_name: auth_mailer_api
    build: .
    ports: 
      - 1111:1111
    volumes: 
      - .:/usr/src/app
    env_file:
    - ./.env
    environment:
      - DB_URI=mongodb://root:example@auth_mailer_mongodb:27017/
    depends_on:
      - mongodb

volumes:
  mongodb: {}