version: '3.9'
services:
  mongodb:
    container_name: auth_mailer_mongodb
    image: mongo:latest
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_DATABASE=auth-mailer
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: